apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: database

  template:
    metadata:
      labels:
        app: database

    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB 
              value: "todo"

          volumeMounts:
              - mountPath: /var/lib/postgresql
                name: db-storage 
              - mountPath: /Docker-entrypoint-initdb.d/
                name: db-init-script-valume
                subPath: init.sql
      volumes:
          - name: db-storage
            persistentVolumeClaim:
              claimName: todoapp-postgres-pvc
          - name: db-init-script-valume
            configMap:
              name: db-init-script-configmap

