apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
    containers:
        - name: backend
          image: backend:latest   
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: database
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: Bolton26
            - name: DB_NAME
              value: todo
            - name: DB_PORT
              value: "5432"
            - name: PORT
              value: "5000"